apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certificates
  namespace: argocd
  labels:
    app-of-apps: "true"
spec:
  project: default
  source:
    repoURL: git@github.com:DamianJaskolski95/k8s-server.git
    path: apps/certificates/prd
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true