apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-spaceship
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:DamianJaskolski95/k8s-server.git
    targetRevision: HEAD
    path: tools/cert-manager-webhook-spaceship/deploy/cert-manager-webhook-spaceship
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true