apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiRGFtaWFuSmFza29sc2tpOTUiLCJwYXNzd29yZCI6ImdocF9iMHZiaHJsWm5XTlZDbXA3SzJrNWptMWpGbUNhaXIwYUdyS2kiLCJlbWFpbCI6Im5vcmVwbHlAZ2l0aHViLmNvbSIsImF1dGgiOiJSR0Z0YVdGdVNtRnphMjlzYzJ0cE9UVTZaMmh3WDJJd2RtSm9jbXhhYmxkT1ZrTnRjRGRMTW1zMWFtMHhha1p0UTJGcGNqQmhSM0pMYVE9PSJ9fX0=
kind: Secret
metadata:
  name: ghcr-secret
  namespace: webapp
type: kubernetes.io/dockerconfigjson
