apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-backend
  namespace: webapp
  labels:
    app: webapp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-backend
  template:
    metadata:
      labels:
        app: webapp-backend
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: webapp-backend
        image: ghcr.io/damianjaskolski95/webapp-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: VPN_INSTANCE_ID
          valueFrom:
            secretKeyRef:
              name: vpn-instance-config
              key: instanceId
        - name: BASIC_AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: webapp-auth
              key: username
        - name: BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: webapp-auth
              key: password
        - name: AWS_REGION
          value: "us-east-1"
        volumeMounts:
        - name: client-cert
          mountPath: /etc/ssl/certs/webapp
          readOnly: true
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      volumes:
      - name: client-cert
        secret:
          secretName: webapp-client-tls