{{- if .Values.mariadb.enabled }}
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: webapp-mariadb
  namespace: {{ .Values.mariadb.namespace | default "webapp" }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  username: {{ .Values.mariadb.username | default "webapp_user" }}
  passwordSecretKeyRef:
    name: mariadb-webapp-password
    key: password
  rootPasswordSecretKeyRef:
    name: mariadb-root-password
    key: password

  image: {{ .Values.mariadb.image | default "mariadb:11.4.3" }}
  imagePullPolicy: IfNotPresent

  service:
    type: ClusterIP

  storage:
    size: {{ .Values.mariadb.storage.size | default "10Gi" }}
    storageClassName: ""

  podSecurityContext:
    fsGroup: 999
  securityContext:
    runAsNonRoot: true
    runAsUser: 999
    runAsGroup: 999
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

  {{- if .Values.mariadb.resources }}
  resources:
    {{- if .Values.mariadb.resources.requests }}
    requests:
      {{- if .Values.mariadb.resources.requests.memory }}
      memory: {{ .Values.mariadb.resources.requests.memory }}
      {{- end }}
      {{- if .Values.mariadb.resources.requests.cpu }}
      cpu: {{ .Values.mariadb.resources.requests.cpu }}
      {{- end }}
    {{- end }}
    {{- if .Values.mariadb.resources.limits }}
    limits:
      {{- if .Values.mariadb.resources.limits.memory }}
      memory: {{ .Values.mariadb.resources.limits.memory }}
      {{- end }}
      {{- if .Values.mariadb.resources.limits.cpu }}
      cpu: {{ .Values.mariadb.resources.limits.cpu }}
      {{- end }}
    {{- end }}
  {{- end }}

  replicas: 1
  replication:
    enabled: false

  metrics:
    enabled: false
{{- end }}
