{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: webapp-mariadb-service
  namespace: {{ .Release.Namespace | default "webapp" }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: webapp-mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
  type: ClusterIP
{{- end }}