apiVersion: batch/v1
kind: Job
metadata:
  name: adguard-home-apply-config
spec:
  template:
    spec:
      containers:
      - name: apply-config
        image: curlimages/curl
        command:
        - /bin/sh
        - /scripts/apply-config.sh
        env:
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: adguard-home-git-token
              key: token
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
      - name: scripts
        configMap:
          name: adguard-home-scripts