apiVersion: batch/v1
kind: CronJob
metadata:
  name: adguard-home-backup
spec:
  schedule: "0 2 * * *"  # Run daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: curlimages/curl
            command:
            - /bin/sh
            - /scripts/backup-config.sh
            env:
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: adguard-home-git-token
                  key: token
            volumeMounts:
            - name: scripts
              mountPath: /scripts
          restartPolicy: OnFailure
          volumes:
          - name: scripts
            configMap:
              name: adguard-home-scripts