apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  labels:
    app: adguard-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      initContainers:
      - name: config-init
        image: busybox:latest
        command: ['sh', '-c']
        args:
        - |
          mkdir -p /opt/adguardhome/conf
          mkdir -p /opt/adguardhome/work
          cp /config-init/AdGuardHome.yaml /opt/adguardhome/conf/AdGuardHome.yaml
        volumeMounts:
        - name: config-volume-init
          mountPath: /config-init
        - name: data-volume
          mountPath: /opt/adguardhome
      containers:
      - name: adguard-home
        image: adguard/adguardhome:v0.107.66
        ports:
        - containerPort: 80
          name: http
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        volumeMounts:
        - name: data-volume
          mountPath: /opt/adguardhome
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: config-volume-init
        configMap:
          name: adguard-home-config
      - name: data-volume
        emptyDir: {}