apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  labels:
    app: adguard-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 3000
      initContainers:
      - name: set-permissions
        image: busybox:latest
        command: ['sh', '-c', 'chmod 700 /opt/adguardhome/work && chmod 700 /opt/adguardhome/conf']
        volumeMounts:
        - name: adguard-work
          mountPath: /opt/adguardhome/work
        - name: adguard-conf
          mountPath: /opt/adguardhome/conf
      containers:
      - name: adguard-home
        image: adguard/adguardhome:v0.107.66
        ports:
        - containerPort: 80
          name: http
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 443
          name: https
        - containerPort: 853
          name: dot
        - containerPort: 784
          name: doq
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/adguardhome/tls
          readOnly: true
        - name: adguard-work
          mountPath: /opt/adguardhome/work
        - name: adguard-conf
          mountPath: /opt/adguardhome/conf
      volumes:
      - name: tls-certs
        secret:
          secretName: adguard-home-djasko-com-tls
      - name: adguard-work
        persistentVolumeClaim:
          claimName: adguard-home-work-pvc
      - name: adguard-conf
        persistentVolumeClaim:
          claimName: adguard-home-conf-pvc