apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  labels:
    app: adguard-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      initContainers:
      - name: init-directories
        image: busybox:latest
        command: ['sh', 
                  '-c', 
                  'chown -R 1000:3000 /opt/adguardhome; \
                  chmod -R 700 /opt/adguardhome/work; \
                  chmod 600 /opt/adguardhome/work/data/sessions.db; \
                  echo "done"']
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: adguard-work
          mountPath: /opt/adguardhome/work
        - name: adguard-conf
          mountPath: /opt/adguardhome/conf
      containers:
      - name: adguard-home
        image: adguard/adguardhome:v0.107.66
        ports:
        - containerPort: 80
          name: http
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 443
          name: https
        - containerPort: 853
          name: dot
        - containerPort: 784
          name: doq
        env:
        - name: DISABLE_INIT
          value: "true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/adguardhome/tls
          readOnly: true
        - name: adguard-work
          mountPath: /opt/adguardhome/work
        - name: adguard-conf
          mountPath: /opt/adguardhome/conf
      volumes:
      - name: tls-certs
        secret:
          secretName: adguard-home-djasko-com-tls
      - name: adguard-work
        persistentVolumeClaim:
          claimName: adguard-home-work-pvc
      - name: adguard-conf
        persistentVolumeClaim:
          claimName: adguard-home-conf-pvc