apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adguard-home

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- configmap.yaml
- scripts-configmap.yaml
- backup-cronjob.yaml
- apply-config-job.yaml

generatorOptions:
  disableNameSuffixHash: true