apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- pvc.yaml
- service.yaml
- deployment.yaml
- ingressroute-tcp.yaml
# - ingress-ui.yaml
- install-config-cronjob.yaml
- apply-config-job.yaml
- backup-cronjob.yaml
- configure-encryption-cronjob.yaml

configMapGenerator:
- name: adguard-home-scripts
  files:
  - scripts/backup-config.sh
  - scripts/apply-config.sh
  - scripts/install-config.sh
  - scripts/configure-encryption.sh

generatorOptions:
  disableNameSuffixHash: true

images:
- name: ghcr.io/damianjaskolski95/adguard-home-backup
  newTag: v1.0.0