apiVersion: v1
kind: Service
metadata:
  name: adguard-home
spec:
  selector:
    app: adguard-home
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: setup
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dot
      port: 853
      targetPort: 853
      protocol: TCP
    - name: doq
      port: 784
      targetPort: 784
      protocol: UDP
  type: ClusterIP