apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-34.2.1_up34.2.0
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  ports:
  - name: websecure
    nodePort: 32286
    port: 443
    protocol: TCP
    targetPort: websecure
  - name: dot
    nodePort: 30553
    port: 853
    protocol: TCP
    targetPort: dot
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
  type: LoadBalancer