apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: challenges.acme.cert-manager.io
spec:
  group: acme.cert-manager.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              solver:
                type: object
                properties:
                  groupName:
                    type: string
                  solverName:
                    type: string
  conversion:
    strategy: None
  scope: Namespaced
  names:
    plural: challenges
    singular: challenge
    kind: Challenge
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: orders.acme.cert-manager.io
spec:
  group: acme.cert-manager.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
  conversion:
    strategy: None
  scope: Namespaced
  names:
    plural: orders
    singular: order
    kind: Order