# ArgoCD configuration values
# These values were extracted from the main.tf file to make the configuration cleaner

# Global configuration
global:
  domain: argocd.djasko.com

# Server configuration
server:
  # Service configuration
  service:
    type: NodePort
    servicePortHttp: 80
    servicePortHttps: 443
    nodePorts:
      http: 31080
      https: 31443
  
  # Ingress configuration
  ingress:
    enabled: true
    hostname: argocd.djasko.com
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    extraTls:
      - hosts:
          - argocd.djasko.com
        secretName: argocd-djasko-com-tls
  
  # Server parameters
  config:
    server.insecure: true

# Configuration parameters
configs:
  params:
    server.insecure: true