# ArgoCD configuration values
# These values were extracted from the main.tf file to make the configuration cleaner

# Global configuration
global:
  domain: argocd.djasko.com

# Server configuration
server:
  # Service configuration
  service:
    type: NodePort
    servicePortHttp: 80
    servicePortHttps: 443
    nodePorts:
      http: 31080
      https: 31443
  
  # Ingress configuration
  ingress:
    enabled: true
    hostname: argocd.djasko.com
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    extraTls:
      - hosts:
          - argocd.djasko.com
        secretName: argocd-djasko-com-tls
  
  # Server parameters
  config:
    server.insecure: true
  
  # Resource limits based on actual usage + buffer
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 32Mi

# Configuration parameters
configs:
  params:
    server.insecure: true

# Application Controller configuration
applicationController:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Repo Server configuration
repoServer:
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 32Mi

# Dex Server configuration
dex:
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 16Mi

# Redis configuration
redis:
  resources:
    limits:
      cpu: 50m
      memory: 16Mi
    requests:
      cpu: 10m
      memory: 8Mi