apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-webhook-spaceship
  namespace: cert-manager
  labels:
    app: cert-manager-webhook-spaceship
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-spaceship:domain-solver
  labels:
    app: cert-manager-webhook-spaceship
rules:
  - apiGroups:
      - acme.cert-manager.io
    resources:
      - challenges
    verbs:
      - get
      - list
      - watch
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-spaceship:domain-solver
  labels:
    app: cert-manager-webhook-spaceship
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-spaceship:domain-solver
subjects:
  - name: cert-manager-webhook-spaceship
    namespace: cert-manager
    kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook-spaceship:secret-reader
  namespace: cert-manager
  labels:
    app: cert-manager-webhook-spaceship
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-spaceship:secret-reader
  namespace: cert-manager
  labels:
    app: cert-manager-webhook-spaceship
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-webhook-spaceship:secret-reader
subjects:
  - name: cert-manager-webhook-spaceship
    namespace: cert-manager
    kind: ServiceAccount
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook-spaceship
  namespace: cert-manager
  labels:
    app: cert-manager-webhook-spaceship
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    app: cert-manager-webhook-spaceship
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook-spaceship
  namespace: cert-manager
  labels:
    app: cert-manager-webhook-spaceship
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager-webhook-spaceship
  template:
    metadata:
      labels:
        app: cert-manager-webhook-spaceship
    spec:
      serviceAccountName: cert-manager-webhook-spaceship
      containers:
        - name: cert-manager-webhook-spaceship
          image: cert-manager-webhook-spaceship:latest
          imagePullPolicy: Never
          env:
            - name: GROUP_NAME
              value: "acme.spaceship.com"
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault