{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "vpn-instance-config",
    "namespace": "webapp",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "vpn-instance-config",
        "namespace": "webapp",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "instanceId": "AgBwuGLox5wJLsSRtbpBPIclw/eTl6fDSGEBy1529QO0+A5wd+rbn5Ts2H9fufH4Xipon8pf6GY6q8x7gPYT+WGL5yROko+WobxvUY0DthP40gUi8qYogahIHd5n9hLnelpkLVxfLlKA5bvuf82lWwk9pLTrNVjyD412s6mxsjhHM3/gkmveEUfDy1HHRmVIPg0l0Py9qkmeve8VyFzZQg1R8wi81d734XndBMKX6eGiuvCJEbQsNwxyTVqmPf2BR4Tz0UkSIPErN08ExKWlJdZ6dAUlVVL0ux9kMfasmRiH/skpMbY8D7QrNjJwEvqByxPoVCgG77sLgd38PEDp3Xzxi476pmiqNABCvIPB2Xs33UuJuYZpc5RAFPUU9CYS/x9dwXsTcEm3uxdKHVMG3tO4S+nmzTC/h+Y7WHuqivPjfW6GJlXaHa9CKXL4uAxmxFmyduc0cMC2eNhcg5r8HrIGhZ4g4D10NhA4Td48su8j5YXvhmprSbTEczRH0rLIKq3is+kYIDcI8TcF4HJCxjHcOFOEhyG9XdLbmb5s/4bRoAA0Pq17kLfNxMexRKsxkIA86r8fVRR03amqy/4EkxAcAmBVotsPh0uCOD43+ykI6Hfusl8VlHfCdo0QEo1TT2JYHQ7Q8hCuev7soTEU9cD665/D0Oyr3r2Zkq/H3e6/6/7mio6BG+2zUn26VjHsckDI5LOdlirtTVwPh9Xg5zMdoejS"
    }
  }
}
