name: Cleanup GHCR Images

on:
  schedule:
    - cron: "0 3 * * *" # every day at 3 AM
  workflow_dispatch: # allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Delete old package versions for web-frontend
        uses: actions/delete-package-versions@v5
        with:
          owner: agndam-corp
          package-name: web-frontend
          package-type: container
          min-versions-to-keep: 3
          delete-only-untagged-versions: false
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: Delete old package versions for web-backend
        uses: actions/delete-package-versions@v5
        with:
          owner: agndam-corp
          package-name: web-backend
          package-type: container
          min-versions-to-keep: 3
          delete-only-untagged-versions: false
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: Delete old package versions for adguard-home-backup
        uses: actions/delete-package-versions@v5
        with:
          owner: agndam-corp
          package-name: adguard-home-backup
          package-type: container
          min-versions-to-keep: 3
          delete-only-untagged-versions: false
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: Delete old package versions for cert-manager-webhook-spaceship
        uses: actions/delete-package-versions@v5
        with:
          owner: agndam-corp
          package-name: cert-manager-webhook-spaceship
          package-type: container
          min-versions-to-keep: 3
          delete-only-untagged-versions: false
          token: ${{ secrets.ADMIN_TOKEN }}
